CREATE TABLE conscioussheep_users (
  user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_email VARCHAR(320) NOT NULL UNIQUE,
  user_password TEXT NOT NULL,
  user_zipcode CHAR(5) NOT NULL,
  user_about TEXT,
  user_favortokens INTEGER DEFAULT 1,
  date_created TIMESTAMP NOT NULL DEFAULT now()
);
