DROP TYPE IF EXISTS favor_type;
CREATE TYPE favor_type AS ENUM (
    'Physical',
    'Borrow Items',
    'Intellectual',
    'Emotional'
);

DROP TYPE IF EXISTS favor_status;
CREATE TYPE favor_status AS ENUM (
    'Open',
    'Requested',
    'Pending',
    'Completed'
);

CREATE TABLE conscioussheep_favors (
  favor_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  favor_requester INTEGER REFERENCES conscioussheep_users(user_id),
  favor_fulfiller INTEGER REFERENCES conscioussheep_users(user_id),
  favor_title TEXT NOT NULL,
  favor_description TEXT NOT NULL,
  favor_hoursrequired INTEGER NOT NULL,
  favor_category favor_type NOT NULL,
  favor_status favor_status NOT NULL
);
